In [49]:
import numpy as np

# NUMPY ASSIGNMENT
## Suppose you have a superstore which runs 24/7. Your tasks are to:

**1) Create a dataset of the sale transactions of each day and each hour for the Month of January. Each row contains in the array should contain 23 records. Each index will represent total sale in that hour. e.g row 0 will contain the array of 23 transactions of Jan 1st. Now the 0 index of each row should contain the total sale made at 00:00 hours of respective date.**

In [3]:
data = np.random.randint(low = 1, high = 100, size = (31,24))

In [4]:
data

array([[55,  4, 37, 85, 98, 28, 23, 99, 57, 21,  8, 46, 30, 96, 12, 26,
        70, 56, 45, 61, 39, 32, 44, 44],
       [93,  2, 35, 31, 85, 10, 67, 90,  4, 29,  3, 54, 85, 46, 48, 74,
        41, 50, 91, 25, 97, 45, 14, 36],
       [75, 45, 37,  3, 32, 88, 47, 99, 44, 99,  9, 93, 42, 21, 14,  2,
        81, 44, 24, 79, 13,  6, 22, 58],
       [31, 14, 98, 56, 45, 98, 11, 89, 60, 22, 83, 60, 14, 44, 65, 57,
        69,  6, 40, 13, 81, 61, 50, 14],
       [46, 72, 59, 65, 43,  2, 79, 49, 19, 55, 34, 70, 84, 50, 24, 91,
        93, 66, 46, 19, 45, 52, 20, 64],
       [63, 57, 40, 17, 85, 33, 66, 64, 87,  5, 29, 22, 53, 80, 30, 21,
        79, 83, 22, 55, 20, 31, 11, 92],
       [12, 48, 86, 97, 22, 84, 51, 77, 98, 81, 68, 38, 92, 85, 87, 55,
        11, 13, 18, 50, 39, 99, 21, 74],
       [34, 37, 59, 24, 80,  7, 62, 28, 59, 59, 24, 76,  4, 88, 27, 50,
        49, 37, 34, 77, 78, 20, 23, 91],
       [61, 24, 44, 91, 81, 47, 52, 97, 77, 73, 87, 27, 18, 39, 93, 25,
        87, 16, 77, 82, 

**2) Calculate Daily Average Sale of this dataset**

In [5]:
data.mean(axis = 1)

array([46.5       , 48.125     , 44.875     , 49.20833333, 51.95833333,
       47.70833333, 58.58333333, 46.95833333, 56.75      , 58.04166667,
       45.70833333, 48.        , 47.16666667, 43.83333333, 48.125     ,
       38.66666667, 60.83333333, 52.91666667, 58.41666667, 49.66666667,
       52.41666667, 51.625     , 58.58333333, 58.91666667, 50.29166667,
       43.16666667, 53.66666667, 41.75      , 45.66666667, 45.125     ,
       54.        ])

**3) Calculate the Average Sale of each hour, so that you have insight of the busiest hour in the month.**

In [18]:
data.mean(axis = 1)

array([46.5       , 48.125     , 44.875     , 49.20833333, 51.95833333,
       47.70833333, 58.58333333, 46.95833333, 56.75      , 58.04166667,
       45.70833333, 48.        , 47.16666667, 43.83333333, 48.125     ,
       38.66666667, 60.83333333, 52.91666667, 58.41666667, 49.66666667,
       52.41666667, 51.625     , 58.58333333, 58.91666667, 50.29166667,
       43.16666667, 53.66666667, 41.75      , 45.66666667, 45.125     ,
       54.        ])

**4) Calculate the minimum and Maximum Sale of each day.**

In [8]:
data.min(axis = 1)

array([ 4,  2,  2,  6,  2,  5, 11,  4,  6,  7,  2,  2,  3,  1,  3,  1, 10,
       10,  9,  1,  1,  8,  4, 16,  3,  5,  2,  6,  4,  2,  4])

In [9]:
data.max(axis = 1)

array([99, 97, 99, 98, 93, 92, 99, 91, 97, 97, 98, 92, 98, 91, 93, 94, 96,
       99, 93, 96, 97, 97, 98, 97, 95, 97, 96, 83, 93, 96, 98])

**5) Calculate the Minimum and Maximum Sale of each hour.**

In [10]:
data.min(axis = 0)

array([ 2,  2,  2,  3,  6,  2,  1, 14,  3,  4,  3, 14,  1,  2, 12,  2,  3,
        2,  5,  3,  1,  1,  2,  6])

In [11]:
data.max(axis = 0)

array([93, 95, 98, 97, 98, 98, 90, 99, 98, 99, 97, 98, 92, 96, 99, 94, 96,
       83, 98, 93, 97, 99, 98, 94])

**6) Calculate Daily Cumulative Sum**

In [19]:
data.cumsum(axis = 1)

array([[  55,   59,   96,  181,  279,  307,  330,  429,  486,  507,  515,
         561,  591,  687,  699,  725,  795,  851,  896,  957,  996, 1028,
        1072, 1116],
       [  93,   95,  130,  161,  246,  256,  323,  413,  417,  446,  449,
         503,  588,  634,  682,  756,  797,  847,  938,  963, 1060, 1105,
        1119, 1155],
       [  75,  120,  157,  160,  192,  280,  327,  426,  470,  569,  578,
         671,  713,  734,  748,  750,  831,  875,  899,  978,  991,  997,
        1019, 1077],
       [  31,   45,  143,  199,  244,  342,  353,  442,  502,  524,  607,
         667,  681,  725,  790,  847,  916,  922,  962,  975, 1056, 1117,
        1167, 1181],
       [  46,  118,  177,  242,  285,  287,  366,  415,  434,  489,  523,
         593,  677,  727,  751,  842,  935, 1001, 1047, 1066, 1111, 1163,
        1183, 1247],
       [  63,  120,  160,  177,  262,  295,  361,  425,  512,  517,  546,
         568,  621,  701,  731,  752,  831,  914,  936,  991, 1011, 1042,
       

**7) Calculate Daily Total Sum**

In [20]:
data.sum(axis = 1)

array([1116, 1155, 1077, 1181, 1247, 1145, 1406, 1127, 1362, 1393, 1097,
       1152, 1132, 1052, 1155,  928, 1460, 1270, 1402, 1192, 1258, 1239,
       1406, 1414, 1207, 1036, 1288, 1002, 1096, 1083, 1296])

**8) Use Boolean Indexing to search for records where sale is greater than a defined value, choose an appropriate value depending upon your dataset**

In [21]:
data > 80

array([[False, False, False,  True,  True, False, False,  True, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False],
       [ True, False, False, False,  True, False, False,  True, False,
        False, False, False,  True, False, False, False, False, False,
         True, False,  True, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
         True, False,  True, False, False, False, False,  True, False,
        False, False, False, False, False, False],
       [False, False,  True, False, False,  True, False,  True, False,
        False,  True, False, False, False, False, False, False, False,
        False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False,  True,  True, False,
        False, False, False, False, False, False],
       [False, False, False, False,

**8) Use Boolean Indexing to search for records where sale is greater than a defined value, choose an appropriate value depending upon your dataset**

In [24]:
condition = data > 80
data[condition]

array([85, 98, 99, 96, 93, 85, 90, 85, 91, 97, 88, 99, 99, 93, 81, 98, 98,
       89, 83, 81, 84, 91, 93, 85, 87, 83, 92, 86, 97, 84, 98, 81, 92, 85,
       87, 99, 88, 91, 91, 81, 97, 87, 93, 87, 82, 81, 84, 83, 97, 94, 89,
       93, 91, 93, 98, 84, 81, 84, 83, 92, 96, 87, 98, 89, 94, 89, 83, 91,
       93, 91, 94, 95, 90, 87, 94, 84, 85, 93, 96, 91, 98, 99, 98, 84, 93,
       93, 93, 81, 85, 81, 83, 96, 82, 91, 84, 89, 85, 97, 85, 88, 90, 88,
       84, 82, 97, 92, 88, 84, 95, 89, 91, 98, 88, 95, 92, 91, 97, 86, 88,
       95, 83, 88, 94, 97, 92, 93, 82, 94, 96, 83, 89, 83, 88, 92, 93, 96,
       82, 94, 98, 97, 93])

In [48]:
data_greater80 = len(data[data > 80])
total_hours = len(data.reshape(31*24,1))
print('There are',data_greater80,'hours in which you have sale more then 80rs out of',total_hours)

There are 141 hours in which you have sale more then 80rs out of 744


In [45]:
data.sum(axis = 1)

array([1116, 1155, 1077, 1181, 1247, 1145, 1406, 1127, 1362, 1393, 1097,
       1152, 1132, 1052, 1155,  928, 1460, 1270, 1402, 1192, 1258, 1239,
       1406, 1414, 1207, 1036, 1288, 1002, 1096, 1083, 1296])

In [40]:
data.sum(axis = 1) > 1000

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [42]:
days_sale1000 = len(data.sum(axis = 1)[data.sum(axis = 1) > 1000])
print('There are',days_sale1000,'days in which sale is greater than 1000.')

There are 30 days in which sale is greater than 1000.
